name: Go Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SECRET: IMNOTASECRETLMAO

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum

      - name: Verify and Download dependencies
        run: |
          go mod download
          go mod verify
          apt update -y
          apt install pkg-config libvips-dev -y

      - name: Build the Application
        run: go build -v ./cmd/api

      - name: Run Integration Tests
        run: go test -v ./tests
